# Generated by Django 4.1.3 on 2024-01-04 01:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='Nascimento')),
                ('gender', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMININO'), ('O', 'OUTROS')], max_length=1, verbose_name='Sexo')),
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
